development:
  adapter: postgresql
  encoding: utf8
  database: betterdays_development
  pool: 5
  username: username
  password: password
  host:     <%= ENV['IP'] %>

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: betterdays_test
  pool: 5
  username: username
  password: password
  host:     <%= ENV['IP'] %>

production:
  adapter: postgresql
  encoding: utf8
  database: betterdays_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST